name: Python application

on:
  schedule:
    - cron: '*/15 * * * *'
    - cron: '*/21 * * * *'

env:
  TEST_OUTCOME: ""
  CONTROL: "false"
  DEV_SCHEDULE_PATTERN: '*/15 * * * *'
  PROD_SCHEDULE_PATTERN: '*/21 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set env variable
        id: step1
        run: |
          if ${{ github.event.schedule == env.DEV_SCHEDULE_PATTERN }}; then echo "TEST_ENV=dev" >> "$GITHUB_ENV"; else echo "TEST_ENV=prod" >> "$GITHUB_ENV"; fi
          echo $env.TEST_ENV
          echo ${{ env.TEST_ENV }}
          echo $github.env.TEST_ENV
          echo ${{ github.event.schedule }}
      - name: step2
        run: |
          echo ${{ env.TEST_ENV }}
          echo $env.TEST_ENV
          echo $github.env.TEST_ENV






          
