name: Python application

on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/3 * * * *'
  workflow_dispatch:
      inputs:
        test_set:
          type: choice
          description: 'TEST_SET'
          required: true
          options:
            - regression
            - smoke
          default: 'regression'

env:
  TEST_OUTCOME: ""
  CONTROL: "false"
  DEV_SCHEDULE_PATTERN: '*/2 * * * *'
  PROD_SCHEDULE_PATTERN: '*/3 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set env variable
        id: step1
        run: |
          if ${{ github.event.schedule == env.DEV_SCHEDULE_PATTERN }}; then echo "TEST_ENV=dev" >> "$GITHUB_ENV"; else echo "TEST_ENV=prod" >> "$GITHUB_ENV"; fi
          echo $env.TEST_ENV
          echo ${{ env.TEST_ENV }}
      - name: step2
        run: |
          echo ${{ github.env.TEST_ENV }}






          
