name: Python application

on:
  workflow_dispatch:

env:
  TEST_OUTCOME: ""
  CONTROL: "false"
  DEV_SCHEDULE_PATTERN: '*/15 * * * *'
  PROD_SCHEDULE_PATTERN: '*/21 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    continue-on-error: true
    steps:
      - name: step 1
        continue-on-error: true
        run: |
          sleep 90
      - name: step 2
        timeout-minutes: 2
        continue-on-error: true
        run: |
          sleep 125
      - name: step 3
        continue-on-error: true
        run: |
          sleep 30
      - name: step 4
        continue-on-error: true
        run: |
          sleep 130






          
