name: Python application

on:
  workflow_dispatch:

env:
  TEST_OUTCOME: ""
  CONTROL: "false"
  DEV_SCHEDULE_PATTERN: '*/15 * * * *'
  PROD_SCHEDULE_PATTERN: '*/21 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set env variable
        id: step_1
        run: |
          sleep 30
      - name: step_2
        run: |
          sleep 80
      - name: step_3
        run: |
          sleep 30






          
