name: Python application

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: setup_python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: step1
        id: step1
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: step2
        env:
          SELECTED_COLOR: ${{ steps.step1.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
