name: Python application

on:
  workflow_dispatch:
      inputs:
        test_set:
          type: choice
          description: 'TEST_SET'
          required: true
          options:
            - regression
            - smoke
          default: 'regression'

env:
  TEST_OUTCOME: ""
  CONTROL: "false"
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: setup_python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: step1
        id: step1
        run: |
          echo "TEST_OUTCOME=green" >> "$GITHUB_OUTPUT"
      - name: step2
        env:
          SELECTED_COLOR: ${{ steps.step1.outputs.SELECTED_COLOR }}
        run: |
          if ${{ env.CONTROL }} ; then echo "TEST_OUTCOME=${{ steps.step1.outcome }}" >> $GITHUB_ENV; fi






          
