name: Python application

on:
  workflow_dispatch:

env:
  TEST_OUTCOME: ""
  CONTROL: "false"
  DEV_SCHEDULE_PATTERN: '*/15 * * * *'
  PROD_SCHEDULE_PATTERN: '*/21 * * * *'
  
jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: step 1
        run: |
          sleep 90
      - name: step 2
        run: |
          sleep 125
      - name: step 3
        run: |
          sleep 30






          
