# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
    inputs:
      run_env:
        description: 'Runs on'
        type: choice
        required: true
        options:
          - ubuntu-latest
          - windows-latest
        default: 'ubuntu-latest'

jobs:
  build:

    runs-on: ${{ github.event_name == 'schedule' ? 'ubuntu-latest' :'${{ github.event.inputs.run_env }}'}}
    steps:
    - name: Example
      run: |
        pwd
